### ISSUE TITLE
Tests Fails

### ISSUE THREAD

**Issue by vaibhavhrt** [jamstooks/django-s3-folder-storage#16]
```
$ py manage.py test s3_folder_storage
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
E
======================================================================
ERROR: s3_folder_storage.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: s3_folder_storage.tests
Traceback (most recent call last):
  File "C:\Users\Vaibav\AppData\Local\Programs\Python\Python36\lib\unittest\loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "C:\Users\Vaibhav\AppData\Local\Programs\Python\Python36\lib\unittest\loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "C:\Users\Vaibhav\AppData\Local\Programs\Python\Python36\lib\site-packages\s3_folder_storage\tests\__init__.py", line 1, in <module>
    from s3_folder_storage.tests.testS3 import *
  File "C:\Users\Vaibhav\AppData\Local\Programs\Python\Python36\lib\site-packages\s3_folder_storage\tests\testS3.py", line 54
    print "Write: %s/%s" % (folder, name)
                       ^
SyntaxError: invalid syntax


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

**Comment by darkin1** [comment]
That same on my side. Any fix?

**Comment by vaibhavhrt** [comment]
nope, couldn't figure out any solution so not using this package.
